export const CONTACTUSURL = "https://mealbill.in/contactus";

export const SMALLLOGO = "./images/logo-small.jpg";

export const LOGINBG = "/images/logo-bg.jpg";

// export const RootUrl = "https://api.mealbill.in/";
export const RootUrl = "http://localhost:4000";

// export const RootUrl = "http://localhost:4000";
// export const RootUrl = "https://mealbill.in/api";

export const Curreny = "₹";
let primary = {
  light: "#FFB2A4",
  main: "#F0583C",
  dark: "#e63f20",
};

const secondary = {
  light: "#4c6a85",
  main: "#1C2B38",
  dark: "#11212e",
};

export const userTypes = {
  EXPIRED_SUBSCRIPTION: "EXPIRED_SUBSCRIPTION",

  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAIL: "FORGOT_PASSWORD_FAIL",

  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAIL: "LOGIN_USER_FAIL",

  LOGOUT_USER: "LOGOUT_USER",

  REGISTER_USER: "REGISTER_USER",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAIL: "REGISTER_USER_FAIL",

  GET_USER_DETAILS: "GET_USER_DETAILS",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAIL: "GET_USER_DETAILS_FAIL",

  CREATE_USER: "CREATE_USER",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAIL: "CREATE_USER_FAIL",

  UPDATE_USER: "UPDATE_USER",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAIL: "UPDATE_USER_FAIL",

  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ALL_USERS_SUCCESS: "GET_ALL_USERS_SUCCESS",
  GET_ALL_USERS_FAIL: "GET_ALL_USERS_FAIL",

  DELETE_USER: "DELETE_USER",
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",
  CLOSE_MODAL: "CLOSE_MODAL",
};

export const userGroupTypes = {
  CREATE_USER_GROUP: "CREATE_USER_GROUP",
  CREATE_USER_GROUP_SUCCESS: "CREATE_USER_GROUP_SUCCESS",
  CREATE_USER_GROUP_FAIL: "CREATE_USER_GROUP_FAIL",

  UPDATE_USER_GROUP: "UPDATE_USER_GROUP",
  UPDATE_USER_GROUP_SUCCESS: "UPDATE_USER_GROUP_SUCCESS",
  UPDATE_USER_GROUP_FAIL: "UPDATE_USER_GROUP_FAIL",

  GET_ALL_USER_GROUP: "GET_ALL_USER_GROUP",
  GET_ALL_USER_GROUP_SUCCESS: "GET_ALL_USER_GROUP_SUCCESS",
  GET_ALL_USER_GROUP_FAIL: "GET_ALL_USER_GROUP_FAIL",

  DELETE_USER_GROUP: "DELETE_USER_GROUP",
  DELETE_USER_GROUP_SUCCESS: "DELETE_USER_GROUP_SUCCESS",
  DELETE_USER_GROUP_FAIL: "DELETE_USER_GROUP_FAIL",
  CLOSE_MODAL: "CLOSE_MODAL",
};

export const salonTypes = {
  CREATE_SALON: "CREATE_SALON",
  CREATE_SALON_SUCCESS: "CREATE_SALON_SUCCESS",
  CREATE_SALON_FAIL: "CREATE_SALON_FAIL",

  ASSIGN_SALON_SUBSCRIPTION: "ASSIGN_SALON_SUBSCRIPTION",
  ASSIGN_SALON_SUBSCRIPTION_SUCCESS: "ASSIGN_SALON_SUBSCRIPTION_SUCCESS",
  ASSIGN_SALON_SUBSCRIPTION_FAIL: "ASSIGN_SALON_SUBSCRIPTION_FAIL",

  REMOVE_SALON_SUBSCRIPTION: "REMOVE_SALON_SUBSCRIPTION",
  REMOVE_SALON_SUBSCRIPTION_SUCCESS: "REMOVE_SALON_SUBSCRIPTION_SUCCESS",
  REMOVE_SALON_SUBSCRIPTION_FAIL: "REMOVE_SALON_SUBSCRIPTION_FAIL",

  CREATE_BRANCH: "CREATE_BRANCH",
  CREATE_BRANCH_SUCCESS: "CREATE_BRANCH_SUCCESS",
  CREATE_BRANCH_FAIL: "CREATE_BRANCH_FAIL",

  UPDATE_SALON: "UPDATE_SALON",
  UPDATE_SALON_SUCCESS: "UPDATE_SALON_SUCCESS",
  UPDATE_SALON_FAIL: "UPDATE_SALON_FAIL",

  UPDATE_BRANCH: "UPDATE_BRANCH",
  UPDATE_BRANCH_SUCCESS: "UPDATE_BRANCH_SUCCESS",
  UPDATE_BRANCH_FAIL: "UPDATE_BRANCH_FAIL",

  GET_ALL_SALONS: "GET_ALL_SALONS",
  GET_ALL_SALONS_SUCCESS: "GET_ALL_SALONS_SUCCESS",
  GET_ALL_SALONS_FAIL: "GET_ALL_SALONS_FAIL",

  DELETE_SALON: "DELETE_SALON",
  DELETE_SALON_SUCCESS: "DELETE_SALON_SUCCESS",
  DELETE_SALON_FAIL: "DELETE_SALON_FAIL",

  DELETE_BRANCH: "DELETE_BRANCH",
  DELETE_BRANCH_SUCCESS: "DELETE_BRANCH_SUCCESS",
  DELETE_BRANCH_FAIL: "DELETE_BRANCH_FAIL",

  // REGISTER_USER: "REGISTER_USER",
  // REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  // REGISTER_USER_FAIL: "REGISTER_USER_FAIL",

  // GET_USER_DETAILS: "GET_USER_DETAILS",
  // GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  // GET_USER_DETAILS_FAIL: "GET_USER_DETAILS_FAIL",
  CLOSE_MODAL: "CLOSE_MODAL",

  CREATE_SALON_SERVICES: "CREATE_SALON_SERVICES",
  CREATE_SALON_SERVICES_SUCCESS: "CREATE_SALON_SERVICES_SUCCESS",
  CREATE_SALON_SERVICES_FAIL: "CREATE_SALON_SERVICES_FAIL",

  GET_ALL_SALON_SERVICES: "GET_ALL_SALON_SERVICES",
  GET_ALL_SALON_SERVICES_SUCCESS: "GET_ALL_SALON_SERVICES_SUCCESS",
  GET_ALL_SALON_SERVICES_FAIL: "GET_ALL_SALON_SERVICES_FAIL",

  UPDATE_SALON_SERVICES: "UPDATE_SALON_SERVICES",
  UPDATE_SALON_SERVICES_SUCCESS: "UPDATE_SALON_SERVICES_SUCCESS",
  UPDATE_SALON_SERVICES_FAIL: "UPDATE_SALON_SERVICES_FAIL",

  DELETE_SALON_SERVICES: "DELETE_SALON_SERVICES",
  DELETE_SALON_SERVICES_SUCCESS: "DELETE_SALON_SERVICES_SUCCESS",
  DELETE_SALON_SERVICES_FAIL: "DELETE_SALON_SERVICES_FAIL",

  CREATE_OFFER: "CREATE_OFFER",
  CREATE_OFFER_SUCCESS: "CREATE_OFFER_SUCCESS",
  CREATE_OFFER_FAIL: "CREATE_OFFER_FAIL",

  UPDATE_OFFER: "UPDATE_OFFER",
  UPDATE_OFFER_SUCCESS: "UPDATE_OFFER_SUCCESS",
  UPDATE_OFFER_FAIL: "UPDATE_OFFER_FAIL",

  DELETE_OFFER: "DELETE_OFFER",
  DELETE_OFFER_SUCCESS: "DELETE_OFFER_SUCCESS",
  DELETE_OFFER_FAIL: "DELETE_OFFER_FAIL",

  GET_ALL_OFFERS: "GET_ALL_OFFERS",
  GET_ALL_OFFERS_SUCCESS: "GET_ALL_OFFERS_SUCCESS",
  GET_ALL_OFFERS_FAIL: "GET_ALL_OFFERS_FAIL",

  CREATE_DEAL: "CREATE_DEAL",
  CREATE_DEAL_SUCCESS: "CREATE_DEAL_SUCCESS",
  CREATE_DEAL_FAIL: "CREATE_DEAL_FAIL",

  UPDATE_DEAL: "UPDATE_DEAL",
  UPDATE_DEAL_SUCCESS: "UPDATE_DEAL_SUCCESS",
  UPDATE_DEAL_FAIL: "UPDATE_DEAL_FAIL",

  DELETE_DEAL: "DELETE_DEAL",
  DELETE_DEAL_SUCCESS: "DELETE_DEAL_SUCCESS",
  DELETE_DEAL_FAIL: "DELETE_DEAL_FAIL",

  GET_ALL_DEALS: "GET_ALL_DEALS",
  GET_ALL_DEALS_SUCCESS: "GET_ALL_DEALS_SUCCESS",
  GET_ALL_DEALS_FAIL: "GET_ALL_DEALS_FAIL",
};

export const categoryTypes = {
  CREATE_CATEGORY_TYPE: "CREATE_CATEGORY_TYPE",
  CREATE_CATEGORY_TYPE_SUCCESS: "CREATE_CATEGORY_TYPE_SUCCESS",
  CREATE_CATEGORY_TYPE_FAIL: "CREATE_CATEGORY_TYPE_FAIL",

  IMPORT_CATEGORY: "IMPORT_CATEGORY",
  IMPORT_CATEGORY_SUCCESS: "IMPORT_CATEGORY_SUCCESS",
  IMPORT_CATEGORY_FAIL: "IMPORT_CATEGORY_FAIL",

  UPDATE_CATEGORY_TYPE: "UPDATE_CATEGORY_TYPE",
  UPDATE_CATEGORY_TYPE_SUCCESS: "UPDATE_CATEGORY_TYPE_SUCCESS",
  UPDATE_CATEGORY_TYPE_FAIL: "UPDATE_CATEGORY_TYPE_FAIL",

  GET_ALL_CATEGORY_TYPES: "GET_ALL_CATEGORY_TYPES",
  GET_ALL_CATEGORY_TYPES_SUCCESS: "GET_ALL_CATEGORY_TYPES_SUCCESS",
  GET_ALL_CATEGORY_TYPES_FAIL: "GET_ALL_CATEGORY_TYPES_FAIL",

  DELETE_CATEGORY_TYPE: "DELETE_CATEGORY_TYPE",
  DELETE_CATEGORY_TYPE_SUCCESS: "DELETE_CATEGORY_TYPE_SUCCESS",
  DELETE_CATEGORY_TYPE_FAIL: "DELETE_CATEGORY_TYPE_FAIL",

  CREATE_CATEGORY: "CREATE_CATEGORY",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_FAIL: "CREATE_CATEGORY_FAIL",

  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAIL: "UPDATE_CATEGORY_FAIL",

  GET_ALL_CATEGORYES: "GET_ALL_CATEGORYES",
  GET_ALL_CATEGORYES_SUCCESS: "GET_ALL_CATEGORYES_SUCCESS",
  GET_ALL_CATEGORYES_FAIL: "GET_ALL_CATEGORYES_FAIL",

  GET_SALON_CATEGORIES: "GET_SALON_CATEGORIES",
  GET_SALON_CATEGORIES_SUCCESS: "GET_SALON_CATEGORIES_SUCCESS",
  GET_SALON_CATEGORIES_FAIL: "GET_SALON_CATEGORIES_FAIL",

  GET_BRANCH_CATEGORIES: "GET_BRANCH_CATEGORIES",
  GET_BRANCH_CATEGORIES_SUCCESS: "GET_BRANCH_CATEGORIES_SUCCESS",
  GET_BRANCH_CATEGORIES_FAIL: "GET_BRANCH_CATEGORIES_FAIL",

  DELETE_CATEGORY: "DELETE_CATEGORY",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAIL: "DELETE_CATEGORY_FAIL",
};

export const serviceTypes = {
  CREATE_SERVICE: "CREATE_SERVICE",
  CREATE_SERVICE_SUCCESS: "CREATE_SERVICE_SUCCESS",
  CREATE_SERVICE_FAIL: "CREATE_SERVICE_FAIL",

  IMPORT_SERVICES: "IMPORT_SERVICES",
  IMPORT_SERVICES_SUCCESS: "IMPORT_SERVICES_SUCCESS",
  IMPORT_SERVICES_FAIL: "IMPORT_SERVICES_FAIL",

  UPDATE_SERVICE: "UPDATE_SERVICE",
  UPDATE_SERVICE_SUCCESS: "UPDATE_SERVICE_SUCCESS",
  UPDATE_SERVICE_FAIL: "UPDATE_SERVICE_FAIL",

  GET_SALON_SERVICES: "GET_SALON_SERVICES",
  GET_SALON_SERVICES_SUCCESS: "GET_SALON_SERVICES_SUCCESS",
  GET_SALON_SERVICES_FAIL: "GET_SALON_SERVICES_FAIL",

  GET_BRANCH_SERVICES: "GET_BRANCH_SERVICES",
  GET_BRANCH_SERVICES_SUCCESS: "GET_BRANCH_SERVICES_SUCCESS",
  GET_BRANCH_SERVICES_FAIL: "GET_BRANCH_SERVICES_FAIL",

  DELETE_SERVICE: "DELETE_SERVICE",
  DELETE_SERVICE_SUCCESS: "DELETE_SERVICE_SUCCESS",
  DELETE_SERVICE_FAIL: "DELETE_SERVICE_FAIL",
};

export const hotKeyTypes = {
  CREATE_HOTKEY: "CREATE_HOTKEY",
  CREATE_HOTKEY_SUCCESS: "CREATE_HOTKEY_SUCCESS",
  CREATE_HOTKEY_FAIL: "CREATE_HOTKEY_FAIL",

  UPDATE_HOTKEY: "UPDATE_HOTKEY",
  UPDATE_HOTKEY_SUCCESS: "UPDATE_HOTKEY_SUCCESS",
  UPDATE_HOTKEY_FAIL: "UPDATE_HOTKEY_FAIL",

  GET_ALL_HOTKEYS: "GET_ALL_HOTKEYS",
  GET_ALL_HOTKEYS_SUCCESS: "GET_ALL_HOTKEYS_SUCCESS",
  GET_ALL_HOTKEYS_FAIL: "GET_ALL_HOTKEYS_FAIL",

  DELETE_HOTKEY: "DELETE_HOTKEY",
  DELETE_HOTKEY_SUCCESS: "DELETE_HOTKEY_SUCCESS",
  DELETE_HOTKEY_FAIL: "DELETE_HOTKEY_FAIL",
};
export const branchTypes = {
  CREATE_BRANCH: "CREATE_BRANCH",
  CREATE_BRANCH_SUCCESS: "CREATE_BRANCH_SUCCESS",
  CREATE_BRANCH_FAIL: "CREATE_BRANCH_FAIL",

  UPDATE_BRANCH: "UPDATE_BRANCH",
  UPDATE_BRANCH_SUCCESS: "UPDATE_BRANCH_SUCCESS",
  UPDATE_BRANCH_FAIL: "UPDATE_BRANCH_FAIL",

  GET_ALL_BRANCHES: "GET_ALL_BRANCHES",
  GET_ALL_BRANCHES_SUCCESS: "GET_ALL_BRANCHES_SUCCESS",
  GET_ALL_BRANCHES_FAIL: "GET_ALL_BRANCHES_FAIL",

  DELETE_BRANCH: "DELETE_BRANCH",
  DELETE_BRANCH_SUCCESS: "DELETE_BRANCH_SUCCESS",
  DELETE_BRANCH_FAIL: "DELETE_BRANCH_FAIL",

  CLOSE_MODAL: "CLOSE_MODAL",
};

export const currency = {
  CREATE_CURRENCY: "CREATE_CURRENCY",
  CREATE_CURRENCY_SUCCESS: "CREATE_CURRENCY_SUCCESS",
  CREATE_CURRENCY_FAIL: "CREATE_CURRENCY_FAIL",

  UPDATE_CURRENCY: "UPDATE_CURRENCY",
  UPDATE_CURRENCY_SUCCESS: "UPDATE_CURRENCY_SUCCESS",
  UPDATE_CURRENCY_FAIL: "UPDATE_CURRENCY_FAIL",

  GET_ALL_CURRENCIES: "GET_ALL_CURRENCIES",
  GET_ALL_CURRENCIES_SUCCESS: "GET_ALL_CURRENCIES_SUCCESS",
  GET_ALL_CURRENCIES_FAIL: "GET_ALL_CURRENCIES_FAIL",

  DELETE_CURRENCY: "DELETE_CURRENCY",
  DELETE_CURRENCY_SUCCESS: "DELETE_CURRENCY_SUCCESS",
  DELETE_CURRENCY_FAIL: "DELETE_CURRENCY_FAIL",

  CLOSE_MODAL: "CLOSE_MODAL",
};

export const expenseTypes = {
  IMPORT_EXPENSETYPES: "IMPORT_EXPENSETYPES",
  IMPORT_EXPENSETYPES_SUCCESS: "IMPORT_EXPENSETYPES_SUCCESS",
  IMPORT_EXPENSETYPES_FAIL: "IMPORT_EXPENSETYPES_FAIL",

  CREATE_EXPENSE_TYPE: "CREATE_EXPENSE_TYPE",
  CREATE_EXPENSE_TYPE_SUCCESS: "CREATE_EXPENSE_TYPE_SUCCESS",
  CREATE_EXPENSE_TYPE_FAIL: "CREATE_EXPENSE_TYPE_FAIL",

  UPDATE_EXPENSE_TYPE: "UPDATE_EXPENSE_TYPE",
  UPDATE_EXPENSE_TYPE_SUCCESS: "UPDATE_EXPENSE_TYPE_SUCCESS",
  UPDATE_EXPENSE_TYPE_FAIL: "UPDATE_EXPENSE_TYPE_FAIL",

  GET_ALL_EXPENSE_TYPES: "GET_ALL_EXPENSE_TYPES",
  GET_ALL_EXPENSE_TYPES_SUCCESS: "GET_ALL_EXPENSE_TYPES_SUCCESS",
  GET_ALL_EXPENSE_TYPES_FAIL: "GET_ALL_EXPENSE_TYPES_FAIL",

  GET_SALON_EXPENSE_TYPES: "GET_SALON_EXPENSE_TYPES",
  GET_SALON_EXPENSE_TYPES_SUCCESS: "GET_SALON_EXPENSE_TYPES_SUCCESS",
  GET_SALON_EXPENSE_TYPES_FAIL: "GET_SALON_EXPENSE_TYPES_FAIL",

  DELETE_EXPENSE_TYPE: "DELETE_EXPENSE_TYPE",
  DELETE_EXPENSE_TYPE_SUCCESS: "DELETE_EXPENSE_TYPE_SUCCESS",
  DELETE_EXPENSE_TYPE_FAIL: "DELETE_EXPENSE_TYPE_FAIL",

  CREATE_EXPENSE: "CREATE_EXPENSE",
  CREATE_EXPENSE_SUCCESS: "CREATE_EXPENSE_SUCCESS",
  CREATE_EXPENSE_FAIL: "CREATE_EXPENSE_FAIL",

  UPDATE_EXPENSE: "UPDATE_EXPENSE",
  UPDATE_EXPENSE_SUCCESS: "UPDATE_EXPENSE_SUCCESS",
  UPDATE_EXPENSE_FAIL: "UPDATE_EXPENSE_FAIL",

  GET_ALL_EXPENSES: "GET_ALL_EXPENSES",
  GET_ALL_EXPENSES_SUCCESS: "GET_ALL_EXPENSES_SUCCESS",
  GET_ALL_EXPENSES_FAIL: "GET_ALL_EXPENSES_FAIL",

  DELETE_EXPENSE: "DELETE_EXPENSE",
  DELETE_EXPENSE_SUCCESS: "DELETE_EXPENSE_SUCCESS",
  DELETE_EXPENSE_FAIL: "DELETE_EXPENSE_FAIL",

  CLOSE_MODAL: "CLOSE_MODAL",
};

export const utilTypes = {
  GET_ALL_THEMES: "GET_ALL_THEMES",
  GET_ALL_THEMES_SUCCESS: "GET_ALL_THEMES_SUCCESS",
  GET_ALL_THEMES_FAIL: "GET_ALL_THEMES_FAIL",

  ADD_NEW_THEME: "ADD_NEW_THEME",
  ADD_NEW_THEME_SUCCESS: "ADD_NEW_THEME_SUCCESS",
  ADD_NEW_THEME_FAIL: "ADD_NEW_THEME_FAIL",

  REMOVE_THEME: "REMOVE_THEME",
  REMOVE_THEME_SUCCESS: "REMOVE_THEME_SUCCESS",
  REMOVE_THEME_FAIL: "REMOVE_THEME_FAIL",

  UPDATE_THEME: "UPDATE_THEME",
  UPDATE_THEME_SUCCESS: "UPDATE_THEME_SUCCESS",
  UPDATE_THEME_FAIL: "UPDATE_THEME_FAIL",

  TOGGLE_DRAWER: "TOGGLE_DRAWER",

  TOGGLE_PRINTING: "TOGGLE_PRINTING",

  SET_PRINT_DATA: "SET_PRINT_DATA",

  REMOVE_PRINT_DATA: "REMOVE_PRINT_DATA",

  TOGGLE_FULL_SCREEN: "TOGGLE_FULL_SCREEN",

  OPEN_COMMON_PAGE_MODAL: "OPEN_COMMON_PAGE_MODAL",

  CLOSE_COMMON_PAGE_MODAL: "CLOSE_COMMON_PAGE_MODAL",

  SET_CURRENT_GRAM: "SET_CURRENT_GRAM",
  SET_CURRENT_GRAM_SUCCESS: "SET_CURRENT_GRAM_SUCCESS",
  SET_CURRENT_GRAM_FAIL: "SET_CURRENT_GRAM_FAIL",
  // REGISTER_USER: "REGISTER_USER",
  // REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  // REGISTER_USER_FAIL: "REGISTER_USER_FAIL",

  // GET_USER_DETAILS: "GET_USER_DETAILS",
  // GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  // GET_USER_DETAILS_FAIL: "GET_USER_DETAILS_FAIL",
  TOGGLE_ADVERTISEMENT: "TOGGLE_ADVERTISEMENT",
};

export const commonTypes = {
  GET_ALL_CURRENCIES: "GET_ALL_CURRENCIES",
  GET_ALL_CURRENCIES_SUCCESS: "GET_ALL_CURRENCIES_SUCCESS",
  GET_ALL_CURRENCIES_FAIL: "GET_ALL_CURRENCIES_FAIL",

  GET_ALL_THEMES: "GET_ALL_THEMES",
  GET_ALL_THEMES_SUCCESS: "GET_ALL_THEMES_SUCCESS",
  GET_ALL_THEMES_FAIL: "GET_ALL_THEMES_FAIL",

  ADD_NEW_THEME: "ADD_NEW_THEME",
  ADD_NEW_THEME_SUCCESS: "ADD_NEW_THEME_SUCCESS",
  ADD_NEW_THEME_FAIL: "ADD_NEW_THEME_FAIL",

  REMOVE_THEME: "REMOVE_THEME",
  REMOVE_THEME_SUCCESS: "REMOVE_THEME_SUCCESS",
  REMOVE_THEME_FAIL: "REMOVE_THEME_FAIL",

  UPDATE_THEME: "UPDATE_THEME",
  UPDATE_THEME_SUCCESS: "UPDATE_THEME_SUCCESS",
  UPDATE_THEME_FAIL: "UPDATE_THEME_FAIL",

  GET_ALL_SUBSCRIPTIONS: "GET_ALL_SUBSCRIPTIONS",
  GET_ALL_SUBSCRIPTIONS_SUCCESS: "GET_ALL_SUBSCRIPTIONS_SUCCESS",
  GET_ALL_SUBSCRIPTIONS_FAIL: "GET_ALL_SUBSCRIPTIONS_FAIL",

  ADD_NEW_SUBSCRIPTION: "ADD_NEW_SUBSCRIPTION",
  ADD_NEW_SUBSCRIPTION_SUCCESS: "ADD_NEW_SUBSCRIPTION_SUCCESS",
  ADD_NEW_SUBSCRIPTION_FAIL: "ADD_NEW_SUBSCRIPTION_FAIL",

  REMOVE_SUBSCRIPTION: "REMOVE_SUBSCRIPTION",
  REMOVE_SUBSCRIPTION_SUCCESS: "REMOVE_SUBSCRIPTION_SUCCESS",
  REMOVE_SUBSCRIPTION_FAIL: "REMOVE_SUBSCRIPTION_FAIL",

  UPDATE_SUBSCRIPTION: "UPDATE_SUBSCRIPTION",
  UPDATE_SUBSCRIPTION_SUCCESS: "UPDATE_SUBSCRIPTION_SUCCESS",
  UPDATE_SUBSCRIPTION_FAIL: "UPDATE_SUBSCRIPTION_FAIL",
};

export const orderTypes = {
  SET_ORDER_TYPE: "SET_ORDER_TYPE",

  ACTIVATE_TABLE: "ACTIVATE_TABLE",

  ADD_OTHER_ORDER_TYPE: "ADD_OTHER_ORDER_TYPE",

  SET_ACTIVE_ORDER: "SET_ACTIVE_ORDER",

  PUSH_SERVICE_TO_ORDER: "PUSH_SERVICE_TO_ORDER",
  CHANGE_SERVICE_QUANTITY: "CHANGE_SERVICE_QUANTITY",

  REMOVE_SERVICE: "REMOVE_SERVICE",

  DELETE_LOCAL_ORDER: "DELETE_LOCAL_ORDER",

  CONFIRM_ORDER: "CONFIRM_ORDER",
  CONFIRM_ORDER_SUCCESS: "CONFIRM_ORDER_SUCCESS",
  CONFIRM_ORDER_FAIL: "CONFIRM_ORDER_FAIL",

  GET_PREVIOS_ORDERS: "GET_PREVIOS_ORDERS",
  GET_PREVIOS_ORDERS_SUCCESS: "GET_PREVIOS_ORDERS_SUCCESS",
  GET_PREVIOS_ORDERS_FAIL: "GET_PREVIOS_ORDERS_FAIL",

  GET_ALL_BOOKINGS: "GET_ALL_BOOKINGS",
  GET_ALL_BOOKINGS_SUCCESS: "GET_ALL_BOOKINGS_SUCCESS",
  GET_ALL_BOOKINGS_FAIL: "GET_ALL_BOOKINGS_FAIL",
};

export const reportTypes = {
  GET_REPORT: "GET_REPORT",
  GET_REPORT_SUCCESS: "GET_REPORT_SUCCESS",
  GET_REPORT_FAIL: "GET_REPORT_FAIL",
};

export const customerTypes = {
  GET_ALL_CUSTOMERS: "GET_ALL_CUSTOMERS",
  GET_ALL_CUSTOMERS_SUCCESS: "GET_ALL_CUSTOMERS_SUCCESS",
  GET_ALL_CUSTOMERS_FAIL: "GET_ALL_CUSTOMERS_FAIL",
};

export const dashboardTypes = {
  GET_DASHBOARD: "GET_DASHBOARD",
  GET_DASHBOARD_SUCCESS: "GET_DASHBOARD_SUCCESS",
  GET_DASHBOARD_FAIL: "GET_DASHBOARD_FAIL",
};
